name: metaforge
channels:
  - conda-forge
  - nodefaults
  - hyperthought
dependencies:
  - python=3.8
  - pyside2
  - requests
  - dataclasses-json
  - Pillow>=8.2.0
  - python-dateutil
  - pyyaml
  - h5py
  - hyperthought