# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mjackson/Workspace4/EasyBake/mainwindow.ui',
# licensing of '/Users/mjackson/Workspace4/EasyBake/mainwindow.ui' applies.
#
# Created: Mon Jun 21 13:12:38 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 724)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setContentsMargins(2, 12, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.CreateTemplateTab = QtWidgets.QWidget()
        self.CreateTemplateTab.setObjectName("CreateTemplateTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CreateTemplateTab)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setContentsMargins(4, -1, 4, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dataFileLineEdit = QtWidgets.QLineEdit(self.CreateTemplateTab)
        self.dataFileLineEdit.setText("")
        self.dataFileLineEdit.setReadOnly(True)
        self.dataFileLineEdit.setObjectName("dataFileLineEdit")
        self.horizontalLayout_2.addWidget(self.dataFileLineEdit)
        self.dataFileSelect = QtWidgets.QPushButton(self.CreateTemplateTab)
        self.dataFileSelect.setObjectName("dataFileSelect")
        self.horizontalLayout_2.addWidget(self.dataFileSelect)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dataTypeLabel = QtWidgets.QLabel(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTypeLabel.sizePolicy().hasHeightForWidth())
        self.dataTypeLabel.setSizePolicy(sizePolicy)
        self.dataTypeLabel.setObjectName("dataTypeLabel")
        self.horizontalLayout_3.addWidget(self.dataTypeLabel)
        self.dataTypeText = QtWidgets.QLabel(self.CreateTemplateTab)
        self.dataTypeText.setObjectName("dataTypeText")
        self.horizontalLayout_3.addWidget(self.dataTypeText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileParserLabel = QtWidgets.QLabel(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileParserLabel.sizePolicy().hasHeightForWidth())
        self.fileParserLabel.setSizePolicy(sizePolicy)
        self.fileParserLabel.setObjectName("fileParserLabel")
        self.horizontalLayout.addWidget(self.fileParserLabel)
        self.fileParserCombo = QtWidgets.QComboBox(self.CreateTemplateTab)
        self.fileParserCombo.setObjectName("fileParserCombo")
        self.fileParserCombo.addItem("")
        self.fileParserCombo.addItem("")
        self.fileParserCombo.addItem("")
        self.horizontalLayout.addWidget(self.fileParserCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.appendCreateTableRowButton = QtWidgets.QToolButton(self.CreateTemplateTab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/plus@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appendCreateTableRowButton.setIcon(icon)
        self.appendCreateTableRowButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.appendCreateTableRowButton.setObjectName("appendCreateTableRowButton")
        self.horizontalLayout.addWidget(self.appendCreateTableRowButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.widget_3 = QtWidgets.QWidget(self.CreateTemplateTab)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_5.addWidget(self.widget_3, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.createTemplateTreeSearchBar = QtWidgets.QLineEdit(self.CreateTemplateTab)
        self.createTemplateTreeSearchBar.setObjectName("createTemplateTreeSearchBar")
        self.gridLayout.addWidget(self.createTemplateTreeSearchBar, 0, 0, 1, 1)
        self.createTemplateListSearchBar = QtWidgets.QLineEdit(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTemplateListSearchBar.sizePolicy().hasHeightForWidth())
        self.createTemplateListSearchBar.setSizePolicy(sizePolicy)
        self.createTemplateListSearchBar.setObjectName("createTemplateListSearchBar")
        self.gridLayout.addWidget(self.createTemplateListSearchBar, 0, 1, 1, 1)
        self.metadataTreeView = QtWidgets.QTreeView(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataTreeView.sizePolicy().hasHeightForWidth())
        self.metadataTreeView.setSizePolicy(sizePolicy)
        self.metadataTreeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.metadataTreeView.setAlternatingRowColors(True)
        self.metadataTreeView.setObjectName("metadataTreeView")
        self.gridLayout.addWidget(self.metadataTreeView, 1, 0, 1, 1)
        self.metadataTableView = QtWidgets.QTableView(self.CreateTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataTableView.sizePolicy().hasHeightForWidth())
        self.metadataTableView.setSizePolicy(sizePolicy)
        self.metadataTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.metadataTableView.setAlternatingRowColors(True)
        self.metadataTableView.setObjectName("metadataTableView")
        self.metadataTableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.metadataTableView, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 3, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.CreateTemplateTab)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_11.setSpacing(2)
        self.horizontalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_10.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(1227, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.saveTemplateButton = QtWidgets.QPushButton(self.widget_2)
        self.saveTemplateButton.setObjectName("saveTemplateButton")
        self.horizontalLayout_10.addWidget(self.saveTemplateButton)
        self.horizontalLayout_11.addWidget(self.widget_2)
        self.gridLayout_5.addWidget(self.widget, 4, 0, 1, 2)
        self.TabWidget.addTab(self.CreateTemplateTab, "")
        self.UseTemplateTab = QtWidgets.QWidget()
        self.UseTemplateTab.setObjectName("UseTemplateTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.UseTemplateTab)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.useTemplateListView = QtWidgets.QListView(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useTemplateListView.sizePolicy().hasHeightForWidth())
        self.useTemplateListView.setSizePolicy(sizePolicy)
        self.useTemplateListView.setMinimumSize(QtCore.QSize(325, 0))
        self.useTemplateListView.setAcceptDrops(True)
        self.useTemplateListView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.useTemplateListView.setAlternatingRowColors(False)
        self.useTemplateListView.setObjectName("useTemplateListView")
        self.horizontalLayout_13.addWidget(self.useTemplateListView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hyperthoughtTemplateLabel = QtWidgets.QLabel(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hyperthoughtTemplateLabel.sizePolicy().hasHeightForWidth())
        self.hyperthoughtTemplateLabel.setSizePolicy(sizePolicy)
        self.hyperthoughtTemplateLabel.setObjectName("hyperthoughtTemplateLabel")
        self.horizontalLayout_5.addWidget(self.hyperthoughtTemplateLabel)
        self.hyperthoughtTemplateLineEdit = QtWidgets.QLineEdit(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hyperthoughtTemplateLineEdit.sizePolicy().hasHeightForWidth())
        self.hyperthoughtTemplateLineEdit.setSizePolicy(sizePolicy)
        self.hyperthoughtTemplateLineEdit.setReadOnly(True)
        self.hyperthoughtTemplateLineEdit.setObjectName("hyperthoughtTemplateLineEdit")
        self.horizontalLayout_5.addWidget(self.hyperthoughtTemplateLineEdit)
        self.hyperthoughtTemplateSelect = QtWidgets.QPushButton(self.UseTemplateTab)
        self.hyperthoughtTemplateSelect.setObjectName("hyperthoughtTemplateSelect")
        self.horizontalLayout_5.addWidget(self.hyperthoughtTemplateSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.otherDataFileLineEdit = QtWidgets.QLineEdit(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherDataFileLineEdit.sizePolicy().hasHeightForWidth())
        self.otherDataFileLineEdit.setSizePolicy(sizePolicy)
        self.otherDataFileLineEdit.setReadOnly(True)
        self.otherDataFileLineEdit.setObjectName("otherDataFileLineEdit")
        self.horizontalLayout_6.addWidget(self.otherDataFileLineEdit)
        self.otherDataFileSelect = QtWidgets.QPushButton(self.UseTemplateTab)
        self.otherDataFileSelect.setEnabled(True)
        self.otherDataFileSelect.setObjectName("otherDataFileSelect")
        self.horizontalLayout_6.addWidget(self.otherDataFileSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.usetableSearchBar = QtWidgets.QLineEdit(self.UseTemplateTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usetableSearchBar.sizePolicy().hasHeightForWidth())
        self.usetableSearchBar.setSizePolicy(sizePolicy)
        self.usetableSearchBar.setReadOnly(False)
        self.usetableSearchBar.setObjectName("usetableSearchBar")
        self.horizontalLayout_12.addWidget(self.usetableSearchBar)
        self.displayedFileLabel = QtWidgets.QLabel(self.UseTemplateTab)
        self.displayedFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayedFileLabel.setObjectName("displayedFileLabel")
        self.horizontalLayout_12.addWidget(self.displayedFileLabel)
        self.appendUseTableRowButton = QtWidgets.QToolButton(self.UseTemplateTab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appendUseTableRowButton.setIcon(icon1)
        self.appendUseTableRowButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.appendUseTableRowButton.setObjectName("appendUseTableRowButton")
        self.horizontalLayout_12.addWidget(self.appendUseTableRowButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.useTemplateTableView = QtWidgets.QTableView(self.UseTemplateTab)
        self.useTemplateTableView.setAlternatingRowColors(True)
        self.useTemplateTableView.setObjectName("useTemplateTableView")
        self.useTemplateTableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.useTemplateTableView)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.UseTemplateTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.hyperthoughtLocationLineEdit = QtWidgets.QLineEdit(self.UseTemplateTab)
        self.hyperthoughtLocationLineEdit.setText("")
        self.hyperthoughtLocationLineEdit.setObjectName("hyperthoughtLocationLineEdit")
        self.horizontalLayout_7.addWidget(self.hyperthoughtLocationLineEdit)
        self.hyperthoughtLocationButton = QtWidgets.QPushButton(self.UseTemplateTab)
        self.hyperthoughtLocationButton.setEnabled(True)
        self.hyperthoughtLocationButton.setObjectName("hyperthoughtLocationButton")
        self.horizontalLayout_7.addWidget(self.hyperthoughtLocationButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.hyperthoughtUploadButton = QtWidgets.QPushButton(self.UseTemplateTab)
        self.hyperthoughtUploadButton.setEnabled(False)
        self.hyperthoughtUploadButton.setObjectName("hyperthoughtUploadButton")
        self.gridLayout_2.addWidget(self.hyperthoughtUploadButton, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.TabWidget.addTab(self.UseTemplateTab, "")
        self.gridLayout_4.addWidget(self.TabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1216, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenPackage = QtWidgets.QAction(MainWindow)
        self.actionOpenPackage.setEnabled(True)
        self.actionOpenPackage.setObjectName("actionOpenPackage")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setEnabled(False)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionSave_Package = QtWidgets.QAction(MainWindow)
        self.actionSave_Package.setEnabled(True)
        self.actionSave_Package.setObjectName("actionSave_Package")
        self.actionSave_Package_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Package_As.setEnabled(True)
        self.actionSave_Package_As.setObjectName("actionSave_Package_As")
        self.actionUse_Template = QtWidgets.QAction(MainWindow)
        self.actionUse_Template.setCheckable(True)
        self.actionUse_Template.setEnabled(True)
        self.actionUse_Template.setObjectName("actionUse_Template")
        self.actionCreate_Template = QtWidgets.QAction(MainWindow)
        self.actionCreate_Template.setCheckable(True)
        self.actionCreate_Template.setChecked(True)
        self.actionCreate_Template.setEnabled(True)
        self.actionCreate_Template.setObjectName("actionCreate_Template")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave_Template = QtWidgets.QAction(MainWindow)
        self.actionSave_Template.setObjectName("actionSave_Template")
        self.actionOpen_Template = QtWidgets.QAction(MainWindow)
        self.actionOpen_Template.setObjectName("actionOpen_Template")
        self.menuFile.addAction(self.actionOpenPackage)
        self.menuFile.addAction(self.actionOpen_Template)
        self.menuFile.addAction(self.actionOpen_Recent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Package)
        self.menuFile.addAction(self.actionSave_Package_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Template)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Data File:", None, -1))
        self.dataFileSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select data file to use for meta-data extraction", None, -1))
        self.dataFileSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.dataTypeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Data Type Detected:", None, -1))
        self.dataTypeText.setText(QtWidgets.QApplication.translate("MainWindow", "None Selected", None, -1))
        self.fileParserLabel.setText(QtWidgets.QApplication.translate("MainWindow", "File Parser:", None, -1))
        self.fileParserCombo.setProperty("currentText", QtWidgets.QApplication.translate("MainWindow", "CTF Parser", None, -1))
        self.fileParserCombo.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "CTF Parser", None, -1))
        self.fileParserCombo.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "ANG Parser", None, -1))
        self.fileParserCombo.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Custom Parser", None, -1))
        self.appendCreateTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a custom value to the template", None, -1))
        self.appendCreateTableRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Custom Value", None, -1))
        self.createTemplateTreeSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Type to search for key", None, -1))
        self.createTemplateListSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Type to search for key", None, -1))
        self.saveTemplateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save Template as ...", None, -1))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.CreateTemplateTab), QtWidgets.QApplication.translate("MainWindow", "Create Template", None, -1))
        self.hyperthoughtTemplateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Template File: ", None, -1))
        self.hyperthoughtTemplateLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "example.ez", None, -1))
        self.hyperthoughtTemplateSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select the template file for this upload(*.ez)", None, -1))
        self.hyperthoughtTemplateSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "File To Extract Metadata From: ", None, -1))
        self.otherDataFileSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select a data file to extract meta-data", None, -1))
        self.otherDataFileSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.usetableSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search For HT Key", None, -1))
        self.displayedFileLabel.setText(QtWidgets.QApplication.translate("MainWindow", "No File Selected", None, -1))
        self.appendUseTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a Custom Value that is only going to be used for this upload", None, -1))
        self.appendUseTableRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Custom Value", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "HyperThought Uploader Folder", None, -1))
        self.hyperthoughtLocationLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Use the \'Select Remote Folder\' button to set the remote location for the data --->", None, -1))
        self.hyperthoughtLocationButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Allows user to set their API key from HyperThought and set a remote location on the HyperThought server to upload the data files", None, -1))
        self.hyperthoughtLocationButton.setText(QtWidgets.QApplication.translate("MainWindow", "Select Remote Folder", None, -1))
        self.hyperthoughtUploadButton.setText(QtWidgets.QApplication.translate("MainWindow", "Upload Files", None, -1))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.UseTemplateTab), QtWidgets.QApplication.translate("MainWindow", "Use Template", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionOpenPackage.setText(QtWidgets.QApplication.translate("MainWindow", "Open Package", None, -1))
        self.actionOpen_Recent.setText(QtWidgets.QApplication.translate("MainWindow", "Open Recent", None, -1))
        self.actionSave_Package.setText(QtWidgets.QApplication.translate("MainWindow", "Save Package", None, -1))
        self.actionSave_Package_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save Package As", None, -1))
        self.actionUse_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Use Template", None, -1))
        self.actionCreate_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Create Template", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close ", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionSave_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Save Template", None, -1))
        self.actionOpen_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Restore Template", None, -1))

import resources_rc
