{% set setup_data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: metaforge
  version: {{ setup_data.get('version') }}

source:
  # git_rev: rc-13
  # git_url: https://github.com/BlueQuartzSoftware/MetaForge.git
  #[source information here]
  # folder: my-destination/folder
  path: ../

requirements:
  build:
    - python
  run:
    - python
    - requests
    - pyside2
    - dataclasses-json
    - pyyaml
    - Pillow>=8.2.0
    - python-dateutil
    - h5py
    - flatten-dict==0.4.2
    - hyperthought

about:
  license: BSD
  home: https://github.com/BlueQuartzSoftware/MetaForge/