# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mjackson/Workspace4/MetaForge/mainwindow.ui',
# licensing of '/Users/mjackson/Workspace4/MetaForge/mainwindow.ui' applies.
#
# Created: Tue Sep 14 17:37:10 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1606, 879)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setContentsMargins(2, 12, 2, 2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.CreateTemplateTab = QtWidgets.QWidget()
        self.CreateTemplateTab.setObjectName("CreateTemplateTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.CreateTemplateTab)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setContentsMargins(4, 12, 4, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.create_frame_3 = QtWidgets.QFrame(self.CreateTemplateTab)
        self.create_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_frame_3.setObjectName("create_frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.create_frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.create_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dataFileLineEdit = QtWidgets.QLineEdit(self.create_frame_3)
        self.dataFileLineEdit.setText("")
        self.dataFileLineEdit.setReadOnly(True)
        self.dataFileLineEdit.setObjectName("dataFileLineEdit")
        self.horizontalLayout_2.addWidget(self.dataFileLineEdit)
        self.dataFileSelect = QtWidgets.QPushButton(self.create_frame_3)
        self.dataFileSelect.setObjectName("dataFileSelect")
        self.horizontalLayout_2.addWidget(self.dataFileSelect)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dataTypeLabel = QtWidgets.QLabel(self.create_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTypeLabel.sizePolicy().hasHeightForWidth())
        self.dataTypeLabel.setSizePolicy(sizePolicy)
        self.dataTypeLabel.setObjectName("dataTypeLabel")
        self.horizontalLayout_3.addWidget(self.dataTypeLabel)
        self.dataTypeText = QtWidgets.QLabel(self.create_frame_3)
        self.dataTypeText.setObjectName("dataTypeText")
        self.horizontalLayout_3.addWidget(self.dataTypeText)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.fileParserLabel = QtWidgets.QLabel(self.create_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileParserLabel.sizePolicy().hasHeightForWidth())
        self.fileParserLabel.setSizePolicy(sizePolicy)
        self.fileParserLabel.setObjectName("fileParserLabel")
        self.horizontalLayout_3.addWidget(self.fileParserLabel)
        self.fileParserCombo = QtWidgets.QComboBox(self.create_frame_3)
        self.fileParserCombo.setCurrentText("")
        self.fileParserCombo.setObjectName("fileParserCombo")
        self.horizontalLayout_3.addWidget(self.fileParserCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.create_frame_3, 0, 0, 1, 2)
        self.create_frame_4 = QtWidgets.QFrame(self.CreateTemplateTab)
        self.create_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_frame_4.setObjectName("create_frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.create_frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearCreateButton = QtWidgets.QPushButton(self.create_frame_4)
        self.clearCreateButton.setObjectName("clearCreateButton")
        self.horizontalLayout.addWidget(self.clearCreateButton)
        spacerItem2 = QtWidgets.QSpacerItem(1227, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveTemplateButton = QtWidgets.QPushButton(self.create_frame_4)
        self.saveTemplateButton.setDefault(False)
        self.saveTemplateButton.setFlat(False)
        self.saveTemplateButton.setObjectName("saveTemplateButton")
        self.horizontalLayout.addWidget(self.saveTemplateButton)
        self.gridLayout_5.addWidget(self.create_frame_4, 5, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.create_frame_2 = QtWidgets.QFrame(self.CreateTemplateTab)
        self.create_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_frame_2.setObjectName("create_frame_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.create_frame_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.create_label_2 = QtWidgets.QLabel(self.create_frame_2)
        self.create_label_2.setObjectName("create_label_2")
        self.horizontalLayout_5.addWidget(self.create_label_2)
        self.createTemplateTreeSearchBar = QtWidgets.QLineEdit(self.create_frame_2)
        self.createTemplateTreeSearchBar.setObjectName("createTemplateTreeSearchBar")
        self.horizontalLayout_5.addWidget(self.createTemplateTreeSearchBar)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.metadataTreeView = QtWidgets.QTreeView(self.create_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataTreeView.sizePolicy().hasHeightForWidth())
        self.metadataTreeView.setSizePolicy(sizePolicy)
        self.metadataTreeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.metadataTreeView.setAlternatingRowColors(True)
        self.metadataTreeView.setObjectName("metadataTreeView")
        self.gridLayout_9.addWidget(self.metadataTreeView, 1, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.create_frame_2)
        self.create_frame_1 = QtWidgets.QFrame(self.CreateTemplateTab)
        self.create_frame_1.setMinimumSize(QtCore.QSize(200, 0))
        self.create_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_frame_1.setObjectName("create_frame_1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.create_frame_1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.metadataTableView = QtWidgets.QTableView(self.create_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metadataTableView.sizePolicy().hasHeightForWidth())
        self.metadataTableView.setSizePolicy(sizePolicy)
        self.metadataTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.metadataTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.metadataTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.metadataTableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.metadataTableView.setProperty("showDropIndicator", False)
        self.metadataTableView.setDragDropOverwriteMode(False)
        self.metadataTableView.setAlternatingRowColors(True)
        self.metadataTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.metadataTableView.setShowGrid(False)
        self.metadataTableView.setSortingEnabled(True)
        self.metadataTableView.setCornerButtonEnabled(False)
        self.metadataTableView.setObjectName("metadataTableView")
        self.metadataTableView.horizontalHeader().setStretchLastSection(True)
        self.metadataTableView.verticalHeader().setVisible(False)
        self.metadataTableView.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_8.addWidget(self.metadataTableView, 2, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 3, 0, 1, 1)
        self.removeCreateTableRowButton = QtWidgets.QPushButton(self.create_frame_1)
        self.removeCreateTableRowButton.setMinimumSize(QtCore.QSize(40, 0))
        self.removeCreateTableRowButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.removeCreateTableRowButton.setText("")
        self.removeCreateTableRowButton.setObjectName("removeCreateTableRowButton")
        self.gridLayout_8.addWidget(self.removeCreateTableRowButton, 3, 2, 1, 1)
        self.appendCreateTableRowButton = QtWidgets.QPushButton(self.create_frame_1)
        self.appendCreateTableRowButton.setMinimumSize(QtCore.QSize(40, 0))
        self.appendCreateTableRowButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.appendCreateTableRowButton.setText("")
        self.appendCreateTableRowButton.setObjectName("appendCreateTableRowButton")
        self.gridLayout_8.addWidget(self.appendCreateTableRowButton, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.create_label_1 = QtWidgets.QLabel(self.create_frame_1)
        self.create_label_1.setObjectName("create_label_1")
        self.horizontalLayout_4.addWidget(self.create_label_1)
        self.createTemplateListSearchBar = QtWidgets.QLineEdit(self.create_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTemplateListSearchBar.sizePolicy().hasHeightForWidth())
        self.createTemplateListSearchBar.setSizePolicy(sizePolicy)
        self.createTemplateListSearchBar.setObjectName("createTemplateListSearchBar")
        self.horizontalLayout_4.addWidget(self.createTemplateListSearchBar)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 1, 0, 1, 3)
        self.horizontalLayout_6.addWidget(self.create_frame_1)
        self.horizontalLayout_6.setStretch(0, 25)
        self.horizontalLayout_6.setStretch(1, 75)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.TabWidget.addTab(self.CreateTemplateTab, "")
        self.UseTemplateTab = QtWidgets.QWidget()
        self.UseTemplateTab.setObjectName("UseTemplateTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.UseTemplateTab)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setContentsMargins(4, 12, 4, 4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.use_frame_3 = QtWidgets.QFrame(self.UseTemplateTab)
        self.use_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.use_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.use_frame_3.setObjectName("use_frame_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.use_frame_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.addUploadFilesBtn = QtWidgets.QPushButton(self.use_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addUploadFilesBtn.sizePolicy().hasHeightForWidth())
        self.addUploadFilesBtn.setSizePolicy(sizePolicy)
        self.addUploadFilesBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.addUploadFilesBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.addUploadFilesBtn.setText("")
        self.addUploadFilesBtn.setObjectName("addUploadFilesBtn")
        self.gridLayout_10.addWidget(self.addUploadFilesBtn, 2, 0, 1, 1)
        self.clearUploadFilesBtn = QtWidgets.QPushButton(self.use_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearUploadFilesBtn.sizePolicy().hasHeightForWidth())
        self.clearUploadFilesBtn.setSizePolicy(sizePolicy)
        self.clearUploadFilesBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.clearUploadFilesBtn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.clearUploadFilesBtn.setText("")
        self.clearUploadFilesBtn.setObjectName("clearUploadFilesBtn")
        self.gridLayout_10.addWidget(self.clearUploadFilesBtn, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 2, 2, 1, 1)
        self.useTemplateListView = QtWidgets.QListView(self.use_frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useTemplateListView.sizePolicy().hasHeightForWidth())
        self.useTemplateListView.setSizePolicy(sizePolicy)
        self.useTemplateListView.setMinimumSize(QtCore.QSize(325, 0))
        self.useTemplateListView.setAcceptDrops(True)
        self.useTemplateListView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.useTemplateListView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.useTemplateListView.setAlternatingRowColors(True)
        self.useTemplateListView.setUniformItemSizes(True)
        self.useTemplateListView.setObjectName("useTemplateListView")
        self.gridLayout_10.addWidget(self.useTemplateListView, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.use_frame_3)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 3)
        self.horizontalLayout_13.addWidget(self.use_frame_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.use_frame_1 = QtWidgets.QFrame(self.UseTemplateTab)
        self.use_frame_1.setAutoFillBackground(False)
        self.use_frame_1.setStyleSheet("")
        self.use_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.use_frame_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.use_frame_1.setObjectName("use_frame_1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.use_frame_1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.otherDataFileSelect = QtWidgets.QPushButton(self.use_frame_1)
        self.otherDataFileSelect.setEnabled(True)
        self.otherDataFileSelect.setObjectName("otherDataFileSelect")
        self.gridLayout_7.addWidget(self.otherDataFileSelect, 1, 2, 1, 1)
        self.use_label_1 = QtWidgets.QLabel(self.use_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_label_1.sizePolicy().hasHeightForWidth())
        self.use_label_1.setSizePolicy(sizePolicy)
        self.use_label_1.setObjectName("use_label_1")
        self.gridLayout_7.addWidget(self.use_label_1, 0, 0, 1, 1)
        self.hyperthoughtTemplateLineEdit = QtWidgets.QLineEdit(self.use_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hyperthoughtTemplateLineEdit.sizePolicy().hasHeightForWidth())
        self.hyperthoughtTemplateLineEdit.setSizePolicy(sizePolicy)
        self.hyperthoughtTemplateLineEdit.setReadOnly(True)
        self.hyperthoughtTemplateLineEdit.setObjectName("hyperthoughtTemplateLineEdit")
        self.gridLayout_7.addWidget(self.hyperthoughtTemplateLineEdit, 0, 1, 1, 1)
        self.use_label_2 = QtWidgets.QLabel(self.use_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.use_label_2.sizePolicy().hasHeightForWidth())
        self.use_label_2.setSizePolicy(sizePolicy)
        self.use_label_2.setObjectName("use_label_2")
        self.gridLayout_7.addWidget(self.use_label_2, 1, 0, 1, 1)
        self.hyperthoughtTemplateSelect = QtWidgets.QPushButton(self.use_frame_1)
        self.hyperthoughtTemplateSelect.setObjectName("hyperthoughtTemplateSelect")
        self.gridLayout_7.addWidget(self.hyperthoughtTemplateSelect, 0, 2, 1, 1)
        self.otherDataFileLineEdit = QtWidgets.QLineEdit(self.use_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherDataFileLineEdit.sizePolicy().hasHeightForWidth())
        self.otherDataFileLineEdit.setSizePolicy(sizePolicy)
        self.otherDataFileLineEdit.setReadOnly(True)
        self.otherDataFileLineEdit.setObjectName("otherDataFileLineEdit")
        self.gridLayout_7.addWidget(self.otherDataFileLineEdit, 1, 1, 1, 1)
        self.addMetadataFileCheckBox = QtWidgets.QCheckBox(self.use_frame_1)
        self.addMetadataFileCheckBox.setChecked(True)
        self.addMetadataFileCheckBox.setObjectName("addMetadataFileCheckBox")
        self.gridLayout_7.addWidget(self.addMetadataFileCheckBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.use_frame_1)
        self.use_frame_2 = QtWidgets.QFrame(self.UseTemplateTab)
        self.use_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.use_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.use_frame_2.setObjectName("use_frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.use_frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.useTemplateTableView = QtWidgets.QTableView(self.use_frame_2)
        self.useTemplateTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.useTemplateTableView.setAlternatingRowColors(True)
        self.useTemplateTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.useTemplateTableView.setShowGrid(False)
        self.useTemplateTableView.setGridStyle(QtCore.Qt.SolidLine)
        self.useTemplateTableView.setSortingEnabled(True)
        self.useTemplateTableView.setCornerButtonEnabled(False)
        self.useTemplateTableView.setObjectName("useTemplateTableView")
        self.useTemplateTableView.horizontalHeader().setStretchLastSection(True)
        self.useTemplateTableView.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_6.addWidget(self.useTemplateTableView, 1, 0, 1, 4)
        self.use_label_3 = QtWidgets.QLabel(self.use_frame_2)
        self.use_label_3.setObjectName("use_label_3")
        self.gridLayout_6.addWidget(self.use_label_3, 0, 0, 1, 1)
        self.removeUseTableRowButton = QtWidgets.QPushButton(self.use_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeUseTableRowButton.sizePolicy().hasHeightForWidth())
        self.removeUseTableRowButton.setSizePolicy(sizePolicy)
        self.removeUseTableRowButton.setMinimumSize(QtCore.QSize(40, 0))
        self.removeUseTableRowButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.removeUseTableRowButton.setText("")
        self.removeUseTableRowButton.setObjectName("removeUseTableRowButton")
        self.gridLayout_6.addWidget(self.removeUseTableRowButton, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 0, 1, 2)
        self.appendUseTableRowButton = QtWidgets.QPushButton(self.use_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appendUseTableRowButton.sizePolicy().hasHeightForWidth())
        self.appendUseTableRowButton.setSizePolicy(sizePolicy)
        self.appendUseTableRowButton.setMinimumSize(QtCore.QSize(40, 0))
        self.appendUseTableRowButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.appendUseTableRowButton.setText("")
        self.appendUseTableRowButton.setObjectName("appendUseTableRowButton")
        self.gridLayout_6.addWidget(self.appendUseTableRowButton, 2, 2, 1, 1)
        self.useTemplateListSearchBar = QtWidgets.QLineEdit(self.use_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useTemplateListSearchBar.sizePolicy().hasHeightForWidth())
        self.useTemplateListSearchBar.setSizePolicy(sizePolicy)
        self.useTemplateListSearchBar.setReadOnly(False)
        self.useTemplateListSearchBar.setObjectName("useTemplateListSearchBar")
        self.gridLayout_6.addWidget(self.useTemplateListSearchBar, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.use_frame_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.horizontalLayout_13.setStretch(1, 100)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 0, 1, 1)
        self.use_frame_4 = QtWidgets.QFrame(self.UseTemplateTab)
        self.use_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.use_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.use_frame_4.setObjectName("use_frame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.use_frame_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.clearUseButton = QtWidgets.QPushButton(self.use_frame_4)
        self.clearUseButton.setObjectName("clearUseButton")
        self.gridLayout_11.addWidget(self.clearUseButton, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.hyperThoughtServer = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.hyperThoughtServer.setFont(font)
        self.hyperThoughtServer.setObjectName("hyperThoughtServer")
        self.horizontalLayout_7.addWidget(self.hyperThoughtServer)
        spacerItem7 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.label_4 = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.hyperThoughtProject = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.hyperThoughtProject.setFont(font)
        self.hyperThoughtProject.setObjectName("hyperThoughtProject")
        self.horizontalLayout_7.addWidget(self.hyperThoughtProject)
        spacerItem8 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.label_5 = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.hyperThoughtUploadPath = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.hyperThoughtUploadPath.setFont(font)
        self.hyperThoughtUploadPath.setObjectName("hyperThoughtUploadPath")
        self.horizontalLayout_7.addWidget(self.hyperThoughtUploadPath)
        spacerItem9 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.label_6 = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.hyperThoughtExpiresIn = QtWidgets.QLabel(self.use_frame_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.hyperThoughtExpiresIn.setFont(font)
        self.hyperThoughtExpiresIn.setObjectName("hyperThoughtExpiresIn")
        self.horizontalLayout_7.addWidget(self.hyperThoughtExpiresIn)
        spacerItem10 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.hyperthoughtLocationButton = QtWidgets.QPushButton(self.use_frame_4)
        self.hyperthoughtLocationButton.setEnabled(True)
        self.hyperthoughtLocationButton.setObjectName("hyperthoughtLocationButton")
        self.horizontalLayout_7.addWidget(self.hyperthoughtLocationButton)
        self.hyperthoughtUploadButton = QtWidgets.QPushButton(self.use_frame_4)
        self.hyperthoughtUploadButton.setEnabled(False)
        self.hyperthoughtUploadButton.setObjectName("hyperthoughtUploadButton")
        self.horizontalLayout_7.addWidget(self.hyperthoughtUploadButton)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.gridLayout_3.addWidget(self.use_frame_4, 2, 0, 1, 1)
        self.TabWidget.addTab(self.UseTemplateTab, "")
        self.gridLayout_4.addWidget(self.TabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1606, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen_Recent = QtWidgets.QMenu(self.menuFile)
        self.menuOpen_Recent.setObjectName("menuOpen_Recent")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenPackage = QtWidgets.QAction(MainWindow)
        self.actionOpenPackage.setEnabled(True)
        self.actionOpenPackage.setObjectName("actionOpenPackage")
        self.actionSave_Package = QtWidgets.QAction(MainWindow)
        self.actionSave_Package.setEnabled(True)
        self.actionSave_Package.setObjectName("actionSave_Package")
        self.actionSave_Package_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Package_As.setEnabled(True)
        self.actionSave_Package_As.setObjectName("actionSave_Package_As")
        self.actionUse_Template = QtWidgets.QAction(MainWindow)
        self.actionUse_Template.setCheckable(True)
        self.actionUse_Template.setEnabled(True)
        self.actionUse_Template.setObjectName("actionUse_Template")
        self.actionCreate_Template = QtWidgets.QAction(MainWindow)
        self.actionCreate_Template.setCheckable(True)
        self.actionCreate_Template.setChecked(True)
        self.actionCreate_Template.setEnabled(True)
        self.actionCreate_Template.setObjectName("actionCreate_Template")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave_Template = QtWidgets.QAction(MainWindow)
        self.actionSave_Template.setObjectName("actionSave_Template")
        self.actionOpen_Template = QtWidgets.QAction(MainWindow)
        self.actionOpen_Template.setObjectName("actionOpen_Template")
        self.actionPackages = QtWidgets.QAction(MainWindow)
        self.actionPackages.setCheckable(True)
        self.actionPackages.setChecked(True)
        self.actionPackages.setObjectName("actionPackages")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen_Template)
        self.menuFile.addAction(self.actionOpenPackage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Template)
        self.menuFile.addAction(self.actionSave_Package)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Data File:", None, -1))
        self.dataFileSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select data file to use for meta-data extraction", None, -1))
        self.dataFileSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.dataTypeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Data Type Detected:", None, -1))
        self.dataTypeText.setText(QtWidgets.QApplication.translate("MainWindow", "None", None, -1))
        self.fileParserLabel.setText(QtWidgets.QApplication.translate("MainWindow", "File Parser:", None, -1))
        self.clearCreateButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reset all \'Create Template\' input fields. All fields will be reset to an empty state.", None, -1))
        self.clearCreateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Reset All Fields", None, -1))
        self.saveTemplateButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Save Values to a .ez template file. You can also use standard \'Save\' Shortcut key", None, -1))
        self.saveTemplateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save Template as ...", None, -1))
        self.create_label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Search Table", None, -1))
        self.createTemplateTreeSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search metadata keys using wildcard (*.*)", None, -1))
        self.removeCreateTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a custom value to the template", None, -1))
        self.appendCreateTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a custom value to the template", None, -1))
        self.create_label_1.setText(QtWidgets.QApplication.translate("MainWindow", "Search Table", None, -1))
        self.createTemplateListSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search table using wildcard (*.*)", None, -1))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.CreateTemplateTab), QtWidgets.QApplication.translate("MainWindow", "Create Template", None, -1))
        self.addUploadFilesBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add files to the upload list", None, -1))
        self.clearUploadFilesBtn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Clear *all* the files from the list", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Files to be Uploaded:", None, -1))
        self.otherDataFileSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select a data file to extract meta-data", None, -1))
        self.otherDataFileSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.use_label_1.setText(QtWidgets.QApplication.translate("MainWindow", "Template File: ", None, -1))
        self.hyperthoughtTemplateLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Drag a template file here or select one using the \'Select\' button to the right===>", None, -1))
        self.use_label_2.setText(QtWidgets.QApplication.translate("MainWindow", "File To Extract Metadata From: ", None, -1))
        self.hyperthoughtTemplateSelect.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select the template file for this upload(*.ez)", None, -1))
        self.hyperthoughtTemplateSelect.setText(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.addMetadataFileCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Add Extracted Metadata File To File List", None, -1))
        self.use_label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Search Table", None, -1))
        self.removeUseTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Removes the selected rows from the table", None, -1))
        self.appendUseTableRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a Custom Value that is only going to be used for this upload", None, -1))
        self.useTemplateListSearchBar.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search table using wildcard (*.*)", None, -1))
        self.clearUseButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reset all \'Create Template\' input fields. All fields will be reset to an empty state.", None, -1))
        self.clearUseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Reset All Fields", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Server:", None, -1))
        self.hyperThoughtServer.setText(QtWidgets.QApplication.translate("MainWindow", "Server Not Selected", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Project:", None, -1))
        self.hyperThoughtProject.setText(QtWidgets.QApplication.translate("MainWindow", "Project Not Selected", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Project Directory Path:", None, -1))
        self.hyperThoughtUploadPath.setText(QtWidgets.QApplication.translate("MainWindow", "Folder Not Selected", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Token Expires At:", None, -1))
        self.hyperThoughtExpiresIn.setText(QtWidgets.QApplication.translate("MainWindow", "Not Authenticated", None, -1))
        self.hyperthoughtLocationButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Allows user to set their API key from HyperThought and set a remote location on the HyperThought server to upload the data files", None, -1))
        self.hyperthoughtLocationButton.setText(QtWidgets.QApplication.translate("MainWindow", "Select Remote Folder", None, -1))
        self.hyperthoughtUploadButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Upload all files to the HyperThought server", None, -1))
        self.hyperthoughtUploadButton.setText(QtWidgets.QApplication.translate("MainWindow", "Upload Files", None, -1))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.UseTemplateTab), QtWidgets.QApplication.translate("MainWindow", "Use Template", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuOpen_Recent.setTitle(QtWidgets.QApplication.translate("MainWindow", "Open Recent", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionOpenPackage.setText(QtWidgets.QApplication.translate("MainWindow", "Open Package", None, -1))
        self.actionOpenPackage.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, -1))
        self.actionSave_Package.setText(QtWidgets.QApplication.translate("MainWindow", "Save Package", None, -1))
        self.actionSave_Package.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.actionSave_Package_As.setText(QtWidgets.QApplication.translate("MainWindow", "Save Package As", None, -1))
        self.actionUse_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Use Template", None, -1))
        self.actionCreate_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Create Template", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close ", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionHelp.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+H", None, -1))
        self.actionSave_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Save Template", None, -1))
        self.actionSave_Template.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionOpen_Template.setText(QtWidgets.QApplication.translate("MainWindow", "Open Template", None, -1))
        self.actionOpen_Template.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionPackages.setText(QtWidgets.QApplication.translate("MainWindow", "Packages", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

from . import resources_rc
